### ISSUE TITLE
Dean's List support

### ISSUE THREAD

**Issue by simon-andrews** [simon-andrews/umass-toolkit#7]
UMass maintain's a Dean's List here: http://www.umass.edu/registrar/students/deans-list

Why not automate searching it? Basically, we need a method that works like so:
```
>>> from umass_toolkit import deans_list
>>> deans_list.search("einstein")
[{'name': 'Einstein, Albert', 'honors': True, 'graduation_year': 2022, 'major': 'Physics (BS)'}]
```

Recommended reading:
 * [How HTML forms work (pay attention to the action="..." attribute)](https://www.w3schools.com/html/html_forms.asp)
 * [How HTML tables work](https://www.w3schools.com/html/html_tables.asp)
 * [Using the `requests` library in Python](http://docs.python-requests.org/en/master/user/quickstart/). Pay attention to the part about POST requests (but read the whole page too--it's all good stuff)
 * [How to parse HTML pages with BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)

Recommended knowledge:
 * Comfort with HTML
 * Maybe basic web app development experience?

**Comment by MiloCS** [comment]
Hey I'm a comp sci student at UMass and I'm interested in being added as a contributor and working on this issue

**Comment by simon-andrews** [comment]
Hi! Thanks for your interest, @MiloCS! The best way to get started on this issue would be to fork this repository (which it looks like you've already done [here](https://github.com/MiloCS/umass-toolkit), make your changes in that repository, then make a [pull request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) so your changes can get merged into the main repo.

**Comment by simon-andrews** [comment]
Done in #11. Thank you, @MiloCS!
